feat: Add self updator
eoeo-org/pcsc-rs pull request #453
Opened 2024-09-18 06:26 UTC by kazukazu123123

2024-09-18 07:26 UTC, Mogyuchi requested changes
更新されない

2024-09-18 14:44 UTC, Mogyuchi requested changes
再起動後にターミナルからシグナルを送れない

2024-09-22 16:40 UTC, Mogyuchi commented
一先ず再起動させなくて良いんじゃないか？

2024-10-06 11:58 UTC, Mogyuchi submitted a review, later dismissed

2024-10-06 12:20 UTC, Mogyuchi approved these changes

2024-10-06 12:26 UTC, Zel9278 approved these changes

2024-10-06 12:27 UTC, merged